name: code_assist
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #fonts
  google_fonts: ^6.1.0

  #routing
  go_router: ^10.2.0

  #state management
  flutter_bloc: ^8.1.3

  #service locator
  injectable: ^2.1.2
  get_it: ^7.6.0


  #introduces either types
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  #http request
  dio: ^5.3.2
  retrofit: '>=4.0.0 <5.0.0'

  equatable: ^2.0.5
  collection: ^1.17.2
  flutter_markdown: ^0.6.18+3

  #offline storage
  floor: ^1.4.2

  confetti: ^0.7.0

  flutter_svg: ^2.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

  injectable_generator: ^2.1.6
  build_runner: ^2.3.3
  freezed: ^2.4.1
  json_serializable: ^6.6.2

  retrofit_generator: '>=5.0.0 <6.0.0'

  floor_generator: ^1.4.2

flutter:


  uses-material-design: true

  assets:
  - assets/svgs/bg.svg

